version: "3.3"
name: jackettio
services:

  flaresolverr:
    image: 21hsmw/flaresolverr:nodriver
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    networks:
      - jackettio
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    depends_on:
      - flaresolverr
    networks:
      - jackettio
    restart: unless-stopped
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
  
  comet:
    container_name: comet
    image: g0ldyy/comet
    restart: unless-stopped
    # ports:
    #  - "8000:8000"
    env_file:
      - .commet-env
    volumes:
      - comet_data:/data
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    # add removed rule back (https://github.com/opencontainers/runc/pull/3468)
    device_cgroup_rules:
      - 'c 10:200 rwm'
    # ports:
    #  - "1080:1080"
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
      # - WARP_ENABLE_NAT=1 # enable nat
    cap_add:
      # Docker already have them, these are for podman users
      - MKNOD
      - AUDIT_WRITE
      # additional required cap for warp, both for podman and docker
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
      # uncomment for nat
      # - net.ipv4.ip_forward=1
      # - net.ipv6.conf.all.forwarding=1
      # - net.ipv6.conf.all.accept_ra=2
    volumes:
      - ./data:/var/lib/cloudflare-warp

  jackettio:
    image: ghcr.io/pierre-zachary/jackettio:master
    container_name: jackettio
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DATA_FOLDER=/data
      - JACKETT_URL=http://jackett:9117
    depends_on:
      - jackett
    networks:
      - jackettio
    restart: unless-stopped
    volumes:
      - jackettio-data:/data
    
networks:
  jackettio:

volumes:
  jackett-config:
  jackett-downloads:
  jackettio-data: